### PR TITLE
Descriptive raw file (closes #10)

### LINKED ISSUE #10: File loader for .glraw files
Add loader for .glraw files (raw files with header). Should be similar to RawFile but include access to the key/value pairs in the header

### PR DESCRIPTION
**Pull request by scheibel**
This PR is based on #9.

### CODE REVIEW

**Comment by sbusch42** [comment]
There should be a function to get a list of all keys in the header (getKeys() ...). Otherwise one would need to probe for pre-known header values and it could not contain e.g. a user defined list.

**Comment by sbusch42** [comment]
It would be better if the reload() would just try to reload and not rely on m_valid. For example a file might not exist on the first call, but it can be there on the second call. I would like the function to work then and not just 'remember' the file couldn't be loaded the first time.

Since there is no virtual function in the whole class except the destructor and the class is not likely (or intended) to be subclassed, I would vote for making the destructor non-virtual.

**Comment by scheibel** [comment]
Regarding the `*Keys()` method I would argue that a reader implementation have to rely on explicit header names and types to handle and load defined file types*. However, general introspection (at least for debugging purposes or different styles of programming) is favorable and I will add the missing methods.
I will also change the virtual interface and the reload behavior as you suggested.

\* e.g., the glraw format requires `height` and a `width` fields of type `int` and I can't imagine a loader implementation that searches for something containing `width` of some type and tries to cast it to `int`.

**Comment by scheibel** [comment]
I implemented three accessors for the key lists. If only one accessor should be available we would require further accessors to query the type of header value.

**Pull request merged**
