### PR TITLE
Fix compilation for Visual Studio 2017 v15.5

### PR DESCRIPTION
**Pull request by j-o**
See #41

### CODE REVIEW

**Comment by scheibel** [comment]
Can this be somehow automated? Is it possible to predict a reasonable upper bound to set the limitation to?

**Comment by j-o** [comment]
We could remove the upper bound entirely. This would most likely cause a linker error when this is finally fixed in MSVC, at which point the upper bound could be reintroduced.

**Comment by j-o** [comment]
Guess what, another update...

**Comment by scheibel** [comment]
I suggest removing the upper bound until it gets required.

**Comment by j-o** [comment]
Done

**Pull request merged**
